# Generated by Django 4.2.13 on 2024-06-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('contractor', models.CharField(max_length=100)),
                ('distract', models.CharField(max_length=100)),
                ('materials', models.CharField(max_length=100)),
                ('order_type', models.CharField(choices=[('عداد', 'عداد'), ('تنفيذ شبكة', 'تنفيذ شبكة')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ViolationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='violation_images')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_images', to='home.order')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='object_images')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_images', to='home.order')),
            ],
        ),
        migrations.CreateModel(
            name='AddressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='address_images')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_images', to='home.order')),
            ],
        ),
    ]
