# Generated by Django 4.2.13 on 2024-06-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressimage',
            name='latitude',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressimage',
            name='longitude',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='violationimage',
            name='latitude',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='violationimage',
            name='longitude',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
