# Generated by Django 4.2.13 on 2024-06-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_addressimage_latitude_addressimage_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationimage',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
