# Generated by Django 4.2.9 on 2024-06-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_order_contractor_alter_order_distract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
