# Generated by Django 4.2.9 on 2024-06-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_order_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('عداد', 'عداد'), ('تنفيذ شبكة', 'تنفيذ شبكة'), ('طوارئ', 'طوارئ'), ('إحلال', 'إحلال'), ('التعزيز', 'التعزيز'), ('الجهد المتوسط', 'الجهد المتوسط'), ('المشاريع', 'المشاريع'), ('الملفات الجاهزة', 'الملفات الجاهزة')], max_length=50),
        ),
    ]
