# Generated by Django 4.2.13 on 2024-06-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_order_pdf_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationimage',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
